/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@localhost:5433/governr -t audit_log -t contexts -t model_risks -t models -t organizations -t owners -t risk_categories -s public
 *
 */


export type Json = unknown;
export type audit_action = 'CREATE' | 'DELETE' | 'UPDATE';
export type risk_severity = 'HIGH' | 'LOW' | 'MODERATE';

// Table audit_log
export interface AuditLog {
	id: number;
	model_id: number;
	action: audit_action;
	timestamp: Date;
	user_id: number;
}
export interface AuditLogInput {
	id: number;
	model_id: number;
	action: audit_action;
	timestamp?: Date;
	user_id: number;
}
const audit_log = {
	tableName: 'audit_log',
	columns: ['id', 'model_id', 'action', 'timestamp', 'user_id'],
	requiredForInsert: ['id', 'model_id', 'action', 'user_id'],
	primaryKey: 'id',
	foreignKeys: {
		model_id: { table: 'models', column: 'id', $type: null as unknown as Models },
		user_id: { table: 'owners', column: 'id', $type: null as unknown as Owners },
	},
	$type: null as unknown as AuditLog,
	$input: null as unknown as AuditLogInput
} as const;

// Table contexts
export interface Contexts {
	id: number;
	name: string;
	org_id: number | null;
}
export interface ContextsInput {
	id: number;
	name: string;
	org_id?: number | null;
}
const contexts = {
	tableName: 'contexts',
	columns: ['id', 'name', 'org_id'],
	requiredForInsert: ['id', 'name'],
	primaryKey: 'id',
	foreignKeys: { org_id: { table: 'organizations', column: 'id', $type: null as unknown as Organizations }, },
	$type: null as unknown as Contexts,
	$input: null as unknown as ContextsInput
} as const;

// Table model_risks
export interface ModelRisks {
	id: number;
	model_id: number;
	risk_category_id: number;
	context_id: number;
	severity: risk_severity;
}
export interface ModelRisksInput {
	id: number;
	model_id: number;
	risk_category_id: number;
	context_id: number;
	severity: risk_severity;
}
const model_risks = {
	tableName: 'model_risks',
	columns: ['id', 'model_id', 'risk_category_id', 'context_id', 'severity'],
	requiredForInsert: ['id', 'model_id', 'risk_category_id', 'context_id', 'severity'],
	primaryKey: 'id',
	foreignKeys: {
		model_id: { table: 'models', column: 'id', $type: null as unknown as Models },
		risk_category_id: { table: 'risk_categories', column: 'id', $type: null as unknown as RiskCategories },
		context_id: { table: 'contexts', column: 'id', $type: null as unknown as Contexts },
	},
	$type: null as unknown as ModelRisks,
	$input: null as unknown as ModelRisksInput
} as const;

// Table models
export interface Models {
	id: number;
	name: string;
	owner_id: number;
	org_id: number;
}
export interface ModelsInput {
	id: number;
	name: string;
	owner_id: number;
	org_id: number;
}
const models = {
	tableName: 'models',
	columns: ['id', 'name', 'owner_id', 'org_id'],
	requiredForInsert: ['id', 'name', 'owner_id', 'org_id'],
	primaryKey: 'id',
	foreignKeys: {
		owner_id: { table: 'owners', column: 'id', $type: null as unknown as Owners },
		org_id: { table: 'organizations', column: 'id', $type: null as unknown as Organizations },
	},
	$type: null as unknown as Models,
	$input: null as unknown as ModelsInput
} as const;

// Table organizations
export interface Organizations {
	id: number;
	name: string;
}
export interface OrganizationsInput {
	id: number;
	name: string;
}
const organizations = {
	tableName: 'organizations',
	columns: ['id', 'name'],
	requiredForInsert: ['id', 'name'],
	primaryKey: 'id',
	foreignKeys: {},
	$type: null as unknown as Organizations,
	$input: null as unknown as OrganizationsInput
} as const;

// Table owners
export interface Owners {
	id: number;
	name: string;
	email: string;
	team: string;
	org_id: number;
}
export interface OwnersInput {
	id: number;
	name: string;
	email: string;
	team: string;
	org_id: number;
}
const owners = {
	tableName: 'owners',
	columns: ['id', 'name', 'email', 'team', 'org_id'],
	requiredForInsert: ['id', 'name', 'email', 'team', 'org_id'],
	primaryKey: 'id',
	foreignKeys: { org_id: { table: 'organizations', column: 'id', $type: null as unknown as Organizations }, },
	$type: null as unknown as Owners,
	$input: null as unknown as OwnersInput
} as const;

// Table risk_categories
export interface RiskCategories {
	id: number;
	name: string;
	org_id: number | null;
}
export interface RiskCategoriesInput {
	id: number;
	name: string;
	org_id?: number | null;
}
const risk_categories = {
	tableName: 'risk_categories',
	columns: ['id', 'name', 'org_id'],
	requiredForInsert: ['id', 'name'],
	primaryKey: 'id',
	foreignKeys: { org_id: { table: 'organizations', column: 'id', $type: null as unknown as Organizations }, },
	$type: null as unknown as RiskCategories,
	$input: null as unknown as RiskCategoriesInput
} as const;


export interface TableTypes {
	audit_log: {
		select: AuditLog;
		input: AuditLogInput;
	};
	contexts: {
		select: Contexts;
		input: ContextsInput;
	};
	model_risks: {
		select: ModelRisks;
		input: ModelRisksInput;
	};
	models: {
		select: Models;
		input: ModelsInput;
	};
	organizations: {
		select: Organizations;
		input: OrganizationsInput;
	};
	owners: {
		select: Owners;
		input: OwnersInput;
	};
	risk_categories: {
		select: RiskCategories;
		input: RiskCategoriesInput;
	};
}

export const tables = {
	audit_log,
	contexts,
	model_risks,
	models,
	organizations,
	owners,
	risk_categories,
}
